### ISSUE TITLE
please update for Nextcloud 19 and 20

### ISSUE THREAD

**Issue by h1618** [cweiske/grauphel#83]
Nextcloud 19 is out more than half a year, and Nextcloud 20 a quarter year. Time for a new grauphel release?

**Comment by cweiske** [comment]
You could help verifying that it works on NC19 and 20: https://github.com/cweiske/grauphel/issues/54#issuecomment-361166105

**Comment by mwerle** [comment]
Seems to work fine in Nextcloud 19.

(EDIT: PS: Thank you so much for keeping this maintained.. haven't found any other notetaking app which is as simple to us and cross platform and doesn't require signing up for some random third-party service for syncing.)

**Comment by mwerle** [comment]
Nextcloud 20 fails to synchronise. No errors in the log but packet capturing shows an oauth error:

oauth_problem=signature_invalid&debug_sbs=POST&%01%3A%2F%2F%01%01&oauth_callback%3Dhttp%253A%252F%252Flocalhost%253A8000%252Ftomboy-web-sync%252F%26oauth_consumer_key%3Danyone%26oauth_nonce%3D3930696%26oauth_signature_method%3DHMAC-SHA1%26oauth_timestamp%3D1610866517%26oauth_version%3D1.0

I've been trying to get some more info but not a web developer.

(Using Tomboy 1.15.9 on Windows as client. Tomdroid also fails but can't packet capture that)

**Comment by cweiske** [comment]
It works fine with Nextcloud 19 here.

With Nextcloud 20, auth and sync work here on my development system, but search is broken - because NC 20 has a unified search that needs a new implementation -> #20.

I'll still mark the extension as compatible with NC20.

**Comment by cweiske** [comment]
I've released grauphel 0.7.5.

**Comment by mwerle** [comment]
Thanks for the super-fast update.

JFYI, I had too many other issues with NC20 (many apps displaying blank pages), so it may not have been Grauphel at fault. I rolled back to NC19 and it's still broken.  So it seems I've screwed something up on my system. I'll raise a separate issue.
